language: java
jdk:
  - openjdk8

before_install:
  - chmod +x mvnw

after_success:
    - mvn jacoco:report coveralls:report

branches:
  only:
    - master

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  
script: "./mvnw clean package"

# s3로 알집해서 전송하기
before_deploy:
  - zip -r youtube-server *
  - mkdir -p deploy
  - mv youtube-server.zip deploy/youtube-server.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_ID # Travis repo settings에 설정된 값
    secret_access_key: $AWS_ACCESS_PWD # Travis repo settings에 설정된 값
    bucket: celeb-youtube # S3 버킷
    region: ap-northeast-2 # 아시아 태평양 (서울)
    skip_cleanup: true
    acl: public_read
    local_dir: deploy #zip만 추가하기 위해 s3에 넣을 dir을 deploy 폴더로 지정한다.
    wait-until-deployed: true
    on:
      repo: bactoria/Celeb-Youtube-REST #Github 주소
      branch: master
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_ID # Travis repo settings에 설정된 값
    secret_access_key: $AWS_ACCESS_PWD # Travis repo settings에 설정된 값
    bucket: celeb-youtube # S3 버킷
    key: youtube-server.zip # S3 버킷에 저장된 myBlog.zip 파일을 EC2로 배포
    bundle_type: zip
    application: youtube-service # CodeDeploy 어플리케이션 이름
    deployment_group: youtube-service-group # CodeDeploy 배포 그룹
    region: ap-northeast-2 # 아시아 태평양(서울)
    wait-until-deployed: true
    on:
      repo: bactoria/Celeb-Youtube-REST #Github 주소
      branch: master
 
