language: java
jdk:
  - openjdk8

before_install:
  - chmod +x mvnw

branches:
  only:
    - master

script: "./mvnw clean package"

# s3로 알집해서 전송하기
before_deploy:
  - zip -r youtube-server *
  - mkdir -p deploy
  - mv youtube-server.zip deploy/youtube-server.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: bactoria-youtube-s3 # S3 버킷
    region: ap-northeast-2 # 아시아 태평양 (서울)
    skip_cleanup: true
    acl: public_read
    local_dir: deploy #zip만 추가하기 위해 s3에 넣을 dir을 deploy 폴더로 지정한다.
    wait-until-deployed: true
    on:
      repo: bactoria/Celeb-Youtube-REST #Github 주소
      branch: master
 
